FROM yamlio/alpine-builder:0.0.1

COPY bin/* /export/bin/
COPY yaml-reference-parser/perl/bin/yaml-parser /export/bin/yaml-reference-parser.pl
COPY yaml-reference-parser/perl/lib/* /export/perl5/lib/perl5/
