DOCKER_TAG := 0.0.1
DOCKER_NAME := tester-yaml-reference-parser
DOCKER_DEPS := yaml-reference-parser

include ../../.common.mk

yaml-reference-parser:
	git clone --branch=devel https://github.com/yaml/$@ $@
